# Generated by Django 6.0.3 on 2026-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('website_link', models.URLField(blank=True, max_length=500)),
                ('industry', models.CharField(choices=[('health', 'Health & Wellness'), ('sports', 'Sports Apparel & Gear'), ('nutrition', 'Nutrition & Supplements'), ('local', 'Local Eldoret Business'), ('tech', 'Tech & Fitness Apps'), ('media', 'Media & Content Creation'), ('other', 'Other')], max_length=50)),
                ('collaboration_type', models.CharField(choices=[('sponsor', 'Event Sponsorship'), ('partner', 'Community Partnership'), ('brand', 'Brand Ambassadorship'), ('gear', 'Gear/Product Testing'), ('media', 'Media Coverage')], max_length=50)),
                ('org_email', models.EmailField(max_length=254)),
                ('proposal', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
